### ISSUE TITLE
Use fpm.toml to store LFortran specific configuration

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#377]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/487

This idea came up on the discourse, instead of using a separate configuration file for `lfortran fmt` like `.lfortran-fmt` or similar, the configuration could be stored directly in the `fpm.toml` file.

```toml
[extra]
# unchecked table in package manifest, can contain any data
[extra.lfortran]
# subtable claimed by LFortran compiler
[extra.lfortran.fmt]
# configuration of LFortran reformatter
indent = 3
# ...
```

Let me know whether you find this idea useful for LFortran. 

- Related issues: [fpmhttps://gitlab.com/lfortran/lfortran/-/issues/430](https://github.com/fortran-lang/fpm/issues/430)
- Related patch: [fpmhttps://gitlab.com/lfortran/lfortran/-/issues/533](https://github.com/fortran-lang/fpm/pull/533)
- TOML libraries for C++:
  - [C with C++ bindings](https://github.com/cktan/tomlcpp),
  - [C++17 header-only](https://github.com/marzer/tomlplusplus),
  - [C++11 header-only](https://github.com/ToruNiina/toml11)
