### ISSUE TITLE
`zlib_library` missing while doing clean installation

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5769]
I tried to create a new env and build LFortran. It gave me following error:

```console
% ./build1.sh 
++ pwd
+ cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_LLVM=yes -DLFORTRAN_BUILD_ALL=yes -DWITH_STACKTRACE=yes -DWITH_RUNTIME_STACKTRACE=yes -DWITH_LSP=yes '-DCMAKE_PREFIX_PATH=;/Users/pranavchiku/mambaforge/envs/lf' -DCMAKE_INSTALL_PREFIX=/Users/pranavchiku/repos/lfortran/inst -DCMAKE_INSTALL_LIBDIR=share/lfortran/lib -DCMAKE_EXPORT_COMPILE_COMMANDS=yes -G Ninja .
+ RE2C=/Users/pranavchiku/mambaforge/envs/lf/bin/re2c
+ BISON=/Users/pranavchiku/mambaforge/envs/lf/bin/bison
+ ci/version.sh
++ git describe --tags --dirty
+ version=v0.42.0-633-g5d876beb1-dirty
+ version=0.42.0-633-g5d876beb1-dirty
+ echo 0.42.0-633-g5d876beb1-dirty
+ python src/libasr/asdl_cpp.py grammar/AST.asdl src/lfortran/ast.h
+ python src/libasr/asdl_cpp.py src/libasr/ASR.asdl src/libasr/asr.h
+ python src/libasr/wasm_instructions_visitor.py
Assuming default values of wasm_instructions.txt and wasm_visitor.h
+ python src/libasr/intrinsic_func_registry_util_gen.py
Assuming default values of intrinsic_function_registry_util.h
+ cd src/lfortran
+ /Users/pranavchiku/mambaforge/envs/lf/bin/re2c -W -b parser/tokenizer.re -o parser/tokenizer.cpp
+ cd src/lfortran
+ /Users/pranavchiku/mambaforge/envs/lf/bin/re2c -W -b parser/preprocessor.re -o parser/preprocessor.cpp
+ cd src/lfortran/parser
+ /Users/pranavchiku/mambaforge/envs/lf/bin/bison -Wall -d -r all parser.yy
+ grep -n ''\''' src/lfortran/parser/parser.yy
+ echo OK
OK
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /Users/pranavchiku/mambaforge/envs/lf/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.12")
Call Stack (most recent call first):
  /Users/pranavchiku/mambaforge/envs/lf/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /Users/pranavchiku/mambaforge/envs/lf/share/cmake-3.29/Modules/FindZLIB.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindStaticZLIB.cmake:7 (find_package)
  CMakeLists.txt:128 (find_package)

```

Use `mamba install zlib` to fix it.

I used `ci/environment_linux.yml` to build env

```yaml
name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml=0.10.2
  - pytest=8.1.1
  - jupyter=1.0.0
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test=0.7.0
  - xonsh=0.16.0
  - re2c=3.1
  - numpy=1.26.4
  - bison=3.4
  - rapidjson=1.1.0
  - ninja=1.11.1
  - pandoc=3.1.13
  - kokkos=4.4.01
  - cmake=3.29.1
```
